name: Python CI Pipeline

# This workflow runs on pushes to the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checks out your repository's code
      - name: Check out repository code
        uses: actions/checkout@v3

      # Step 2: Sets up the Python version we want to use
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Installs our project's dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Runs the tests using pytest
      - name: Test with pytest
        run: |
          pytest